#!/data/data/com.termux/files/usr/bin/bash



set -e



echo ""

echo "  Myrient - Instalando no Termux"

echo ""



cd "$HOME"



echo "  [i] Atualizando repositorios..."

pkg update -y



echo "  [i] Atualizando pacotes..."

pkg upgrade -y



echo "  [i] Instalando python, unzip e aria2..."

pkg install -y python unzip aria2



echo "  [i] Baixando FastTelethon.zip..."

curl -L "https://github.com/xw3re/fastcurl/blob/main/FastTelethon.zip?raw=true" -o "$HOME/FastTelethon.zip"



echo "  [i] Descompactando..."

unzip -o "$HOME/FastTelethon.zip" -d "$HOME"

cp -r "$HOME/FastTelethon/"* "$HOME/"

rm -rf "$HOME/FastTelethon" "$HOME/FastTelethon.zip"



echo "  [i] Criando ambiente virtual..."

python -m venv "$HOME/venv"



echo "  [i] Instalando requisitos Python..."

"$HOME/venv/bin/pip" install --upgrade pip

"$HOME/venv/bin/pip" install telethon httpx beautifulsoup4 tgcrypto



echo "  [i] Criando run.sh..."

printf '#!/data/data/com.termux/files/usr/bin/bash

cd "$HOME"

source "$HOME/venv/bin/activate"

python "$HOME/myrient.py"

' > "$HOME/run.sh"

chmod +x "$HOME/run.sh"



echo ""

echo "  [ok] Instalacao concluida! Execute: ./run.sh"

echo ""
